//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotConsole {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Answers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Answers() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BotConsole.Answers", typeof(Answers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для использования в диалоге с ботом: 
        ///Пример 1. /en Привет, как дела?
        ///Пример 2. /ru Hello, how are you?
        ///Для использования в диалоге в других чатах:
        ///Пример 1. @ulingbot /en Привет, как дела?
        ///Пример 2. @ulingbot /ru Hello, how are you?.
        /// </summary>
        internal static string answerExample {
            get {
                return ResourceManager.GetString("answerExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на en - Английский
        ///de - Немецкий
        ///ru - Русский
        ///fr - Французский
        ///ja - Японский
        ///zh - Китайский
        ///es - Испанский
        ///it - Итальянский.
        /// </summary>
        internal static string answerHelp {
            get {
                return ResourceManager.GetString("answerHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для того чтобы использовать бота Вам необходимо:
        ///1.Зайти в чат (конференцию)
        ///2.Отправить сообщение вида:
        ///@ulingbot /[язык] [текст],
        ///где язык обозначается с помощью en, fr и т.д.
        ///Например для отправленного сообщения - 
        ///@ulingbot /en Привет
        ///Результатом будет: Hello
        ///...
        ///4. Готово!
        ///Для того чтобы узнать обозначения языков воспользуйтесь /help.
        /// </summary>
        internal static string answerManual {
            get {
                return ResourceManager.GetString("answerManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добро пожаловать к Вашему личному Карманному переводчику
        ///Используйте кнопку &quot;Руководство&quot;, чтобы узнать как работает переводчик!.
        /// </summary>
        internal static string answerStart {
            get {
                return ResourceManager.GetString("answerStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на I do not understand you, try again.
        /// </summary>
        internal static string answerUnknow {
            get {
                return ResourceManager.GetString("answerUnknow", resourceCulture);
            }
        }
    }
}
